-- Immutable Raw Schema Tables

CREATE TABLE IF NOT EXISTS PA360_DEV.RAW.PATIENTS (
    PATIENT_ID VARCHAR(50),
    NAME VARCHAR(200),
    DATE_OF_BIRTH VARCHAR(50),
    GENDER VARCHAR(10),
    INSURANCE_ID VARCHAR(100),
    PLAN_ID VARCHAR(50),
    CONTACT_NUMBER VARCHAR(20),
    ADDRESS VARCHAR(500),
    ENROLLMENT_STATUS VARCHAR(30),
    PROVISIONAL_RECORD VARCHAR(10),
    LINKED_FROM_PATIENT_ID VARCHAR(50),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_BATCH_ID VARCHAR(100),
    RAW_RECORD_HASH VARCHAR(64),
    RECORD_STATUS VARCHAR(20) DEFAULT 'ACCEPTED'
);

CREATE TABLE IF NOT EXISTS PA360_DEV.RAW.PROVIDERS (
    PROVIDER_ID VARCHAR(50),
    PROVIDER_NAME VARCHAR(200),
    SPECIALTY VARCHAR(100),
    NPI_NUMBER VARCHAR(20),
    PRACTICE_LOCATION VARCHAR(500),
    IS_ACTIVE VARCHAR(10),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_BATCH_ID VARCHAR(100),
    RAW_RECORD_HASH VARCHAR(64),
    RECORD_STATUS VARCHAR(20) DEFAULT 'ACCEPTED'
);

CREATE TABLE IF NOT EXISTS PA360_DEV.RAW.PAYERS (
    PAYER_ID VARCHAR(50),
    PAYER_NAME VARCHAR(200),
    CONTACT_INFO VARIANT,
    IS_ACTIVE VARCHAR(10),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_BATCH_ID VARCHAR(100),
    RAW_RECORD_HASH VARCHAR(64),
    RECORD_STATUS VARCHAR(20) DEFAULT 'ACCEPTED'
);

CREATE TABLE IF NOT EXISTS PA360_DEV.RAW.PLANS (
    PLAN_ID VARCHAR(50),
    PLAN_NAME VARCHAR(200),
    PAYER_ID VARCHAR(50),
    PA_RULES_SUMMARY VARIANT,
    COPAY_INFO VARIANT,
    IS_ACTIVE VARCHAR(10),
    EFFECTIVE_DATE VARCHAR(50),
    TERMINATION_DATE VARCHAR(50),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_BATCH_ID VARCHAR(100),
    RAW_RECORD_HASH VARCHAR(64),
    RECORD_STATUS VARCHAR(20) DEFAULT 'ACCEPTED'
);

CREATE TABLE IF NOT EXISTS PA360_DEV.RAW.SERVICES (
    SERVICE_CODE VARCHAR(20),
    SERVICE_NAME VARCHAR(200),
    SPECIALTY VARCHAR(100),
    AUTHORIZATION_REQUIRED VARCHAR(10),
    TYPICAL_DURATION_DAYS VARCHAR(10),
    NOTES VARCHAR(1000),
    IS_ACTIVE VARCHAR(10),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_BATCH_ID VARCHAR(100),
    RAW_RECORD_HASH VARCHAR(64),
    RECORD_STATUS VARCHAR(20) DEFAULT 'ACCEPTED'
);

CREATE TABLE IF NOT EXISTS PA360_DEV.RAW.AUTHORIZATION_REQUESTS (
    AUTHORIZATION_ID VARCHAR(36),
    PATIENT_ID VARCHAR(50),
    PROVIDER_ID VARCHAR(50),
    PAYER_ID VARCHAR(50),
    PLAN_ID VARCHAR(50),
    SERVICE_CODE VARCHAR(20),
    DIAGNOSIS VARCHAR(20),
    CLINICAL_INDICATION TEXT,
    REQUEST_DATE VARCHAR(50),
    STATUS VARCHAR(50),
    PRIORITY VARCHAR(20),
    MISSING_INFORMATION VARIANT,
    SUPPORTING_DOCUMENT VARCHAR(500),
    SUBMISSION_DATE VARCHAR(50),
    DECISION_DATE VARCHAR(50),
    NOTES TEXT,
    REVIEWED_BY_USER_ID VARCHAR(50),
    AI_CONFIDENCE_SCORE VARCHAR(20),
    AI_SUMMARY TEXT,
    REQUIRES_HUMAN_REVIEW VARCHAR(10),
    HUMAN_REVIEW_REASON TEXT,
    EDGE_CASE_TYPE VARCHAR(50),
    EDGE_CASE_NOTES TEXT,
    IS_RETRO_AUTH VARCHAR(10),
    RETRO_AUTH_REASON TEXT,
    DENIAL_CODE VARCHAR(20),
    DENIAL_REASON TEXT,
    APPEAL_STATUS VARCHAR(50),
    PRIMARY_PAYER_ID VARCHAR(50),
    SECONDARY_PAYER_ID VARCHAR(50),
    COVERAGE_VERIFIED VARCHAR(10),
    COVERAGE_NOTES TEXT,
    REUSED_FROM_AUTHORIZATION_ID VARCHAR(36),
    CLINICAL_CHANGE_DETECTED VARCHAR(10),
    CLINICAL_CHANGE_NOTES TEXT,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_BATCH_ID VARCHAR(100),
    RAW_RECORD_HASH VARCHAR(64),
    RECORD_STATUS VARCHAR(20) DEFAULT 'ACCEPTED'
);

CREATE TABLE IF NOT EXISTS PA360_DEV.RAW.SAMPLE_DOCUMENTS (
    DOCUMENT_ID VARCHAR(36),
    AUTHORIZATION_ID VARCHAR(36),
    DOCUMENT_TYPE VARCHAR(50),
    FILE_NAME VARCHAR(200),
    FILE_PATH VARCHAR(500),
    FILE_SIZE VARCHAR(20),
    MIME_TYPE VARCHAR(100),
    EXTRACTED_TEXT TEXT,
    EXTRACTION_STATUS VARCHAR(20),
    UPLOADED_BY_USER_ID VARCHAR(50),
    UPLOADED_AT VARCHAR(50),
    IS_ACTIVE VARCHAR(10),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_BATCH_ID VARCHAR(100),
    RAW_RECORD_HASH VARCHAR(64),
    RECORD_STATUS VARCHAR(20) DEFAULT 'ACCEPTED'
);

CREATE TABLE IF NOT EXISTS PA360_DEV.RAW.PAYER_RESPONSES (
    RESPONSE_ID VARCHAR(36),
    AUTHORIZATION_ID VARCHAR(36),
    PAYER_ID VARCHAR(50),
    PAYER_NAME VARCHAR(200),
    RESPONSE_TYPE VARCHAR(50),
    RESPONSE_DATE VARCHAR(50),
    RESPONSE_TEXT TEXT,
    RAW_RESPONSE_DATA VARIANT,
    PROCESSED VARCHAR(10),
    PROCESSED_AT VARCHAR(50),
    AI_INTERPRETATION TEXT,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_BATCH_ID VARCHAR(100),
    RAW_RECORD_HASH VARCHAR(64),
    RECORD_STATUS VARCHAR(20) DEFAULT 'ACCEPTED'
);
