-- PA360_APP_USER: Application access
GRANT USAGE ON DATABASE PA360_DEV TO ROLE PA360_APP_USER;
GRANT USAGE ON SCHEMA PA360_DEV.CURATED TO ROLE PA360_APP_USER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PA360_DEV.CURATED TO ROLE PA360_APP_USER;
GRANT SELECT ON ALL VIEWS IN SCHEMA PA360_DEV.CURATED TO ROLE PA360_APP_USER;

-- PA360_APP_READONLY: Reporting access
GRANT USAGE ON DATABASE PA360_DEV TO ROLE PA360_APP_READONLY;
GRANT USAGE ON SCHEMA PA360_DEV.CURATED TO ROLE PA360_APP_READONLY;
GRANT SELECT ON ALL TABLES IN SCHEMA PA360_DEV.CURATED TO ROLE PA360_APP_READONLY;
GRANT SELECT ON ALL VIEWS IN SCHEMA PA360_DEV.CURATED TO ROLE PA360_APP_READONLY;

-- PA360_DPS_PIPELINE: Pipeline access
GRANT USAGE ON DATABASE PA360_DEV TO ROLE PA360_DPS_PIPELINE;
GRANT USAGE ON SCHEMA PA360_DEV.RAW TO ROLE PA360_DPS_PIPELINE;
GRANT USAGE ON SCHEMA PA360_DEV.STAGING TO ROLE PA360_DPS_PIPELINE;
GRANT USAGE ON SCHEMA PA360_DEV.CURATED TO ROLE PA360_DPS_PIPELINE;
GRANT SELECT ON ALL TABLES IN SCHEMA PA360_DEV.RAW TO ROLE PA360_DPS_PIPELINE;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA PA360_DEV.STAGING TO ROLE PA360_DPS_PIPELINE;
GRANT SELECT, INSERT, UPDATE, MERGE ON ALL TABLES IN SCHEMA PA360_DEV.CURATED TO ROLE PA360_DPS_PIPELINE;

-- PA360_ADMIN: Full access
GRANT ALL PRIVILEGES ON DATABASE PA360_DEV TO ROLE PA360_ADMIN;

-- Grant to a hypothetical service account
-- GRANT ROLE PA360_APP_USER TO USER pa360_app_service_account;
