version: '3.9'
services:
  backend:
    volumes:
      - ../../../backend/application-source:/app
    environment:
      - DJANGO_DEBUG=True
    ports:
      - "8000:8000"
      - "5678:5678" # Debug port

  frontend:
    volumes:
      - ../../../frontend/applications/member-portal:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "9229:9229" # Debug port
