CREATE OR REPLACE VIEW PA360_DEV.CURATED.VW_AUTHORIZATION_WORKSPACE AS
SELECT 
    ar.*,
    p.NAME AS PATIENT_NAME, p.DATE_OF_BIRTH, p.INSURANCE_ID, p.ENROLLMENT_STATUS,
    pr.PROVIDER_NAME, pr.SPECIALTY, pr.NPI_NUMBER,
    py.PAYER_NAME,
    pl.PLAN_NAME,
    s.SERVICE_NAME, s.AUTHORIZATION_REQUIRED,
    DATEDIFF('day', ar.REQUEST_DATE, CURRENT_DATE()) AS DAYS_OPEN,
    CASE WHEN ar.STATUS IN ('Submitted', 'Pending') AND DATEDIFF('hour', ar.SUBMISSION_DATE, CURRENT_TIMESTAMP()) > 72 THEN TRUE ELSE FALSE END AS SLA_AT_RISK
FROM PA360_DEV.CURATED.AUTHORIZATION_REQUESTS ar
JOIN PA360_DEV.CURATED.PATIENTS p ON ar.PATIENT_ID = p.PATIENT_ID
JOIN PA360_DEV.CURATED.PROVIDERS pr ON ar.PROVIDER_ID = pr.PROVIDER_ID
JOIN PA360_DEV.CURATED.PAYERS py ON ar.PAYER_ID = py.PAYER_ID
JOIN PA360_DEV.CURATED.PLANS pl ON ar.PLAN_ID = pl.PLAN_ID
JOIN PA360_DEV.CURATED.SERVICES s ON ar.SERVICE_CODE = s.SERVICE_CODE;
