CREATE OR REPLACE VIEW PA360_DEV.CURATED.VW_EXCEPTION_QUEUE AS
SELECT 
    ar.AUTHORIZATION_ID,
    p.NAME AS PATIENT_NAME,
    py.PAYER_NAME,
    s.SERVICE_NAME,
    ar.STATUS,
    ar.EDGE_CASE_TYPE,
    ar.EDGE_CASE_NOTES,
    ar.REQUIRES_HUMAN_REVIEW,
    ar.HUMAN_REVIEW_REASON,
    ar.PRIORITY,
    ar.REQUEST_DATE,
    DATEDIFF('hour', ar.REQUEST_DATE, CURRENT_TIMESTAMP()) AS HOURS_SINCE_REQUEST
FROM PA360_DEV.CURATED.AUTHORIZATION_REQUESTS ar
JOIN PA360_DEV.CURATED.PATIENTS p ON ar.PATIENT_ID = p.PATIENT_ID
JOIN PA360_DEV.CURATED.PAYERS py ON ar.PAYER_ID = py.PAYER_ID
JOIN PA360_DEV.CURATED.SERVICES s ON ar.SERVICE_CODE = s.SERVICE_CODE
WHERE ar.STATUS = 'Exception – Review Required' 
   OR ar.REQUIRES_HUMAN_REVIEW = TRUE 
   OR ar.EDGE_CASE_TYPE != 'NONE';
