CREATE OR REPLACE VIEW PA360_DEV.CURATED.VW_MANAGER_DASHBOARD AS
SELECT 
    py.PAYER_NAME,
    s.SERVICE_NAME,
    COUNT(ar.AUTHORIZATION_ID) AS TOTAL_REQUESTS,
    SUM(CASE WHEN ar.STATUS = 'Denied' THEN 1 ELSE 0 END) AS DENIED_REQUESTS,
    ROUND(SUM(CASE WHEN ar.STATUS = 'Denied' THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(ar.AUTHORIZATION_ID), 0), 2) AS DENIAL_RATE_PERCENT,
    AVG(DATEDIFF('hour', ar.REQUEST_DATE, ar.DECISION_DATE)) AS AVG_TURNAROUND_HOURS,
    SUM(CASE WHEN ar.MISSING_INFORMATION IS NOT NULL THEN 1 ELSE 0 END) AS MISSING_INFO_COUNT,
    SUM(CASE WHEN ar.REQUIRES_HUMAN_REVIEW = TRUE THEN 1 ELSE 0 END) AS HUMAN_REVIEW_COUNT,
    SUM(CASE WHEN sb.BREACH_ID IS NOT NULL THEN 1 ELSE 0 END) AS SLA_BREACH_COUNT
FROM PA360_DEV.CURATED.AUTHORIZATION_REQUESTS ar
JOIN PA360_DEV.CURATED.PAYERS py ON ar.PAYER_ID = py.PAYER_ID
JOIN PA360_DEV.CURATED.SERVICES s ON ar.SERVICE_CODE = s.SERVICE_CODE
LEFT JOIN PA360_DEV.CURATED.SLA_BREACHES sb ON ar.AUTHORIZATION_ID = sb.AUTHORIZATION_ID
GROUP BY py.PAYER_NAME, s.SERVICE_NAME;
