CREATE OR REPLACE TABLE PA360_DEV.MARTS.MART_TURNAROUND_TIME AS
SELECT 
    py.PAYER_NAME,
    s.SERVICE_NAME,
    ar.PRIORITY,
    COUNT(ar.AUTHORIZATION_ID) AS TOTAL_COMPLETED,
    AVG(DATEDIFF('hour', ar.REQUEST_DATE, ar.DECISION_DATE)) AS AVG_TURNAROUND_HOURS,
    SUM(CASE WHEN sb.BREACH_ID IS NULL THEN 1 ELSE 0 END) * 100.0 / NULLIF(COUNT(ar.AUTHORIZATION_ID), 0) AS SLA_COMPLIANCE_PERCENT
FROM PA360_DEV.CURATED.AUTHORIZATION_REQUESTS ar
JOIN PA360_DEV.CURATED.PAYERS py ON ar.PAYER_ID = py.PAYER_ID
JOIN PA360_DEV.CURATED.SERVICES s ON ar.SERVICE_CODE = s.SERVICE_CODE
LEFT JOIN PA360_DEV.CURATED.SLA_BREACHES sb ON ar.AUTHORIZATION_ID = sb.AUTHORIZATION_ID
WHERE ar.STATUS IN ('Approved', 'Denied') AND ar.DECISION_DATE IS NOT NULL
GROUP BY py.PAYER_NAME, s.SERVICE_NAME, ar.PRIORITY;
