CREATE OR REPLACE TABLE PA360_DEV.MARTS.MART_DENIAL_TRENDS AS
SELECT 
    DATE_TRUNC('MONTH', ar.DECISION_DATE) AS DENIAL_MONTH,
    py.PAYER_NAME,
    s.SERVICE_NAME,
    ar.DENIAL_CODE,
    COUNT(ar.AUTHORIZATION_ID) AS DENIAL_COUNT,
    SUM(CASE WHEN ar.APPEAL_STATUS IN ('APPEAL_FILED', 'PEER_TO_PEER_REQUESTED') THEN 1 ELSE 0 END) AS APPEALED_COUNT,
    SUM(CASE WHEN ar.APPEAL_STATUS = 'APPROVED_ON_APPEAL' THEN 1 ELSE 0 END) AS SUCCESSFUL_APPEAL_COUNT
FROM PA360_DEV.CURATED.AUTHORIZATION_REQUESTS ar
JOIN PA360_DEV.CURATED.PAYERS py ON ar.PAYER_ID = py.PAYER_ID
JOIN PA360_DEV.CURATED.SERVICES s ON ar.SERVICE_CODE = s.SERVICE_CODE
WHERE ar.STATUS = 'Denied'
GROUP BY DATE_TRUNC('MONTH', ar.DECISION_DATE), py.PAYER_NAME, s.SERVICE_NAME, ar.DENIAL_CODE;
