CREATE OR REPLACE TABLE PA360_DEV.MARTS.MART_AUTHORIZATION_SUMMARY AS
SELECT 
    DATE_TRUNC('DAY', ar.REQUEST_DATE) AS REPORT_DATE,
    py.PAYER_NAME,
    s.SERVICE_NAME,
    ar.STATUS,
    COUNT(ar.AUTHORIZATION_ID) AS AUTH_COUNT,
    SUM(CASE WHEN ar.PRIORITY = 'EMERGENCY' THEN 1 ELSE 0 END) AS EMERGENCY_COUNT
FROM PA360_DEV.CURATED.AUTHORIZATION_REQUESTS ar
JOIN PA360_DEV.CURATED.PAYERS py ON ar.PAYER_ID = py.PAYER_ID
JOIN PA360_DEV.CURATED.SERVICES s ON ar.SERVICE_CODE = s.SERVICE_CODE
GROUP BY DATE_TRUNC('DAY', ar.REQUEST_DATE), py.PAYER_NAME, s.SERVICE_NAME, ar.STATUS;
