-- Data Quality Validation Queries

-- 1. Required field completeness check per table
SELECT 'AUTHORIZATION_REQUESTS' AS table_name,
       COUNT(*) AS total_records,
       COUNT(AUTHORIZATION_ID) AS valid_auth_ids,
       COUNT(PATIENT_ID) AS valid_patient_ids,
       COUNT(PROVIDER_ID) AS valid_provider_ids
FROM PA360_DEV.STAGING.STG_AUTHORIZATION_REQUESTS
HAVING COUNT(*) != COUNT(AUTHORIZATION_ID) 
    OR COUNT(*) != COUNT(PATIENT_ID)
    OR COUNT(*) != COUNT(PROVIDER_ID);

-- 2. Referential integrity checks
SELECT a.AUTHORIZATION_ID, a.PATIENT_ID
FROM PA360_DEV.STAGING.STG_AUTHORIZATION_REQUESTS a
LEFT JOIN PA360_DEV.STAGING.STG_PATIENTS p ON a.PATIENT_ID = p.PATIENT_ID
WHERE p.PATIENT_ID IS NULL;

-- 3. Duplicate detection queries
SELECT PROVIDER_ID, COUNT(*)
FROM PA360_DEV.STAGING.STG_PROVIDERS
GROUP BY PROVIDER_ID
HAVING COUNT(*) > 1;

-- 4. Format validation
SELECT PROVIDER_ID, NPI_NUMBER
FROM PA360_DEV.STAGING.STG_PROVIDERS
WHERE NPI_NUMBER NOT REGEXP '^[0-9]{10}$';

SELECT AUTHORIZATION_ID, DIAGNOSIS
FROM PA360_DEV.STAGING.STG_AUTHORIZATION_REQUESTS
WHERE DIAGNOSIS NOT REGEXP '^[A-TV-Z][0-9][0-9A-Z]?(\.[0-9A-Z]{1,4})?$'; -- Basic ICD-10 check

-- 5. Reconciliation
SELECT 
    SOURCE_BATCH_ID,
    SUM(CASE WHEN RECORD_STATUS = 'ACCEPTED' THEN 1 ELSE 0 END) AS accepted_count,
    SUM(CASE WHEN RECORD_STATUS = 'REJECTED' THEN 1 ELSE 0 END) AS rejected_count,
    SUM(CASE WHEN RECORD_STATUS = 'DUPLICATE' THEN 1 ELSE 0 END) AS duplicate_count,
    COUNT(*) AS total_ingested_count
FROM PA360_DEV.RAW.PATIENTS
GROUP BY SOURCE_BATCH_ID;
