-- DPS Studio Transformation Scripts (Snowflake SQL)

-- Profile Step:
SELECT 
    COUNT(*) AS TOTAL_RECORDS,
    COUNT(CASE WHEN PATIENT_ID IS NULL THEN 1 END) AS NULL_PATIENT_ID_COUNT,
    COUNT(DISTINCT GENDER) AS DISTINCT_GENDERS
FROM PA360_DEV.RAW.PATIENTS;

-- Validate Step:
UPDATE PA360_DEV.RAW.PROVIDERS
SET RECORD_STATUS = 'REJECTED'
WHERE NPI_NUMBER IS NULL OR LENGTH(NPI_NUMBER) != 10;

-- Cleanse Step:
CREATE OR REPLACE TABLE PA360_DEV.STAGING.STG_PATIENTS AS
SELECT 
    PATIENT_ID,
    TRIM(NAME) AS NAME,
    DATE_OF_BIRTH,
    NULLIF(TRIM(GENDER), '') AS GENDER,
    INSURANCE_ID,
    PLAN_ID,
    CONTACT_NUMBER,
    ADDRESS,
    ENROLLMENT_STATUS,
    PROVISIONAL_RECORD,
    LINKED_FROM_PATIENT_ID,
    INGESTION_TIMESTAMP,
    SOURCE_BATCH_ID
FROM PA360_DEV.RAW.PATIENTS
WHERE RECORD_STATUS = 'ACCEPTED';

-- Standardize Step:
UPDATE PA360_DEV.STAGING.STG_PATIENTS
SET GENDER = CASE 
    WHEN UPPER(GENDER) IN ('M', 'MALE') THEN 'M'
    WHEN UPPER(GENDER) IN ('F', 'FEMALE') THEN 'F'
    ELSE 'O'
END;

-- Dedup Step:
DELETE FROM PA360_DEV.STAGING.STG_PATIENTS
WHERE PATIENT_ID IN (
    SELECT PATIENT_ID
    FROM (
        SELECT PATIENT_ID, 
               ROW_NUMBER() OVER (PARTITION BY PATIENT_ID ORDER BY INGESTION_TIMESTAMP DESC) as rn
        FROM PA360_DEV.STAGING.STG_PATIENTS
    )
    WHERE rn > 1
);

-- Reject routing is handled by checking RECORD_STATUS = 'REJECTED' and moving them to STAGING.REJECTED_RECORDS
CREATE TABLE IF NOT EXISTS PA360_DEV.STAGING.REJECTED_RECORDS (
    RECORD_ID VARCHAR(50),
    TABLE_NAME VARCHAR(50),
    REJECTION_REASON TEXT,
    RAW_DATA VARIANT,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ
);

INSERT INTO PA360_DEV.STAGING.REJECTED_RECORDS (RECORD_ID, TABLE_NAME, REJECTION_REASON)
SELECT PROVIDER_ID, 'PROVIDERS', 'Invalid NPI format or missing required field'
FROM PA360_DEV.RAW.PROVIDERS
WHERE RECORD_STATUS = 'REJECTED';
