# Generated by Django 4.2.28 on 2026-09-21 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '__first__'),
        ('plans', '__first__'),
        ('payers', '__first__'),
        ('patients', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationRequest',
            fields=[
                ('authorization_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('diagnosis', models.CharField(max_length=255)),
                ('clinical_indication', models.TextField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Ready for Submission', 'Ready for Submission'), ('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Additional Info Requested', 'Additional Info Requested'), ('Coverage Validation', 'Coverage Validation'), ('Not Required', 'Not Required'), ('Approved', 'Approved'), ('Service Delivery', 'Service Delivery'), ('Billing / RCM', 'Billing / RCM'), ('Denied', 'Denied'), ('Expired', 'Expired'), ('Existing (Reused)', 'Existing (Reused)'), ('Exception – Review Required', 'Exception – Review Required')], default='Draft', max_length=50)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='ROUTINE', max_length=20)),
                ('missing_information', models.JSONField(blank=True, default=list)),
                ('supporting_document', models.CharField(blank=True, max_length=255, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ai_confidence_score', models.FloatField(blank=True, null=True)),
                ('ai_summary', models.TextField(blank=True)),
                ('requires_human_review', models.BooleanField(default=False)),
                ('human_review_reason', models.TextField(blank=True)),
                ('edge_case_type', models.CharField(choices=[('NONE', 'None'), ('EMERGENCY_RETRO', 'Emergency Retro-Auth'), ('NEWBORN_NEW_ENROLLEE', 'Newborn/New Enrollee'), ('APPROVED_NOT_COVERED', 'Approved but Not Covered'), ('DENIAL_APPEAL', 'Denial/Appeal'), ('CLINICAL_CHANGE', 'Clinical Change'), ('COB', 'Coordination of Benefits')], default='NONE', max_length=50)),
                ('edge_case_notes', models.TextField(blank=True)),
                ('is_retro_auth', models.BooleanField(default=False)),
                ('retro_auth_reason', models.TextField(blank=True)),
                ('denial_code', models.CharField(blank=True, max_length=100)),
                ('denial_reason', models.TextField(blank=True)),
                ('appeal_status', models.CharField(choices=[('NOT_APPLICABLE', 'Not Applicable'), ('APPEAL_FILED', 'Appeal Filed'), ('PEER_TO_PEER_REQUESTED', 'Peer-to-Peer Requested'), ('EXTERNAL_REVIEW_REQUESTED', 'External Review Requested'), ('APPEAL_APPROVED', 'Appeal Approved'), ('APPEAL_DENIED', 'Appeal Denied')], default='NOT_APPLICABLE', max_length=50)),
                ('coverage_verified', models.BooleanField(default=False)),
                ('coverage_notes', models.TextField(blank=True)),
                ('clinical_change_detected', models.BooleanField(default=False)),
                ('clinical_change_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='patients.patient')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='payers.payer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='plans.plan')),
                ('primary_payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_authorizations', to='payers.payer')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='providers.provider')),
                ('reused_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reused_authorizations', to='authorizations.authorizationrequest')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_authorizations', to=settings.AUTH_USER_MODEL)),
                ('secondary_payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_authorizations', to='payers.payer')),
                ('service_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorizationStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Ready for Submission', 'Ready for Submission'), ('Submitted', 'Submitted'), ('Pending', 'Pending'), ('Additional Info Requested', 'Additional Info Requested'), ('Coverage Validation', 'Coverage Validation'), ('Not Required', 'Not Required'), ('Approved', 'Approved'), ('Service Delivery', 'Service Delivery'), ('Billing / RCM', 'Billing / RCM'), ('Denied', 'Denied'), ('Expired', 'Expired'), ('Existing (Reused)', 'Existing (Reused)'), ('Exception – Review Required', 'Exception – Review Required')], max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('authorization_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='authorizations.authorizationrequest')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['changed_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MissingInformationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('present', 'Present'), ('missing', 'Missing'), ('uploaded', 'Uploaded')], default='missing', max_length=20)),
                ('source', models.CharField(choices=[('rules', 'Rules'), ('ai', 'AI')], default='rules', max_length=20)),
                ('authorization_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missing_information_items', to='authorizations.authorizationrequest')),
            ],
            options={
                'unique_together': {('authorization_request', 'item_name')},
            },
        ),
        migrations.AddIndex(
            model_name='authorizationrequest',
            index=models.Index(fields=['status'], name='authorizati_status_8aa380_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizationrequest',
            index=models.Index(fields=['priority'], name='authorizati_priorit_23efa5_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizationrequest',
            index=models.Index(fields=['patient'], name='authorizati_patient_576354_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizationrequest',
            index=models.Index(fields=['payer'], name='authorizati_payer_i_9bef66_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizationrequest',
            index=models.Index(fields=['request_date'], name='authorizati_request_cbf3b6_idx'),
        ),
    ]
