-- Core Load MERGE statements (Idempotent)

MERGE INTO PA360_DEV.CURATED.PATIENTS AS target
USING PA360_DEV.STAGING.STG_PATIENTS AS source
ON target.PATIENT_ID = source.PATIENT_ID
WHEN MATCHED THEN 
    UPDATE SET 
        target.NAME = source.NAME,
        target.DATE_OF_BIRTH = source.DATE_OF_BIRTH,
        target.GENDER = source.GENDER,
        target.INSURANCE_ID = source.INSURANCE_ID,
        target.PLAN_ID = source.PLAN_ID,
        target.CONTACT_NUMBER = source.CONTACT_NUMBER,
        target.ADDRESS = source.ADDRESS,
        target.ENROLLMENT_STATUS = source.ENROLLMENT_STATUS,
        target.UPDATED_AT = CURRENT_TIMESTAMP(),
        target.PIPELINE_VERSION = 'v1.0'
WHEN NOT MATCHED THEN 
    INSERT (PATIENT_ID, NAME, DATE_OF_BIRTH, GENDER, INSURANCE_ID, PLAN_ID, CONTACT_NUMBER, ADDRESS, ENROLLMENT_STATUS, CREATED_AT, PIPELINE_VERSION)
    VALUES (source.PATIENT_ID, source.NAME, source.DATE_OF_BIRTH, source.GENDER, source.INSURANCE_ID, source.PLAN_ID, source.CONTACT_NUMBER, source.ADDRESS, source.ENROLLMENT_STATUS, CURRENT_TIMESTAMP(), 'v1.0');

MERGE INTO PA360_DEV.CURATED.PROVIDERS AS target
USING PA360_DEV.STAGING.STG_PROVIDERS AS source
ON target.PROVIDER_ID = source.PROVIDER_ID
WHEN MATCHED THEN 
    UPDATE SET 
        target.PROVIDER_NAME = source.PROVIDER_NAME,
        target.SPECIALTY = source.SPECIALTY,
        target.NPI_NUMBER = source.NPI_NUMBER,
        target.PRACTICE_LOCATION = source.PRACTICE_LOCATION,
        target.IS_ACTIVE = source.IS_ACTIVE,
        target.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN 
    INSERT (PROVIDER_ID, PROVIDER_NAME, SPECIALTY, NPI_NUMBER, PRACTICE_LOCATION, IS_ACTIVE, CREATED_AT)
    VALUES (source.PROVIDER_ID, source.PROVIDER_NAME, source.SPECIALTY, source.NPI_NUMBER, source.PRACTICE_LOCATION, source.IS_ACTIVE, CURRENT_TIMESTAMP());

-- Similar MERGE statements will be executed for PAYERS, PLANS, SERVICES, AUTHORIZATION_REQUESTS, SAMPLE_DOCUMENTS, PAYER_RESPONSES
