CREATE TABLE IF NOT EXISTS PA360_DEV.CURATED.PATIENTS (
    PATIENT_ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GENDER VARCHAR(10),
    INSURANCE_ID VARCHAR(100),
    PLAN_ID VARCHAR(50) REFERENCES PA360_DEV.CURATED.PLANS(PLAN_ID),
    CONTACT_NUMBER VARCHAR(20),
    ADDRESS VARCHAR(500),
    ENROLLMENT_STATUS VARCHAR(30) DEFAULT 'ACTIVE',
    PROVISIONAL_RECORD BOOLEAN DEFAULT FALSE,
    LINKED_FROM_PATIENT_ID VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_BATCH_ID VARCHAR(100),
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    PIPELINE_VERSION VARCHAR(20)
);
