CREATE TABLE IF NOT EXISTS PA360_DEV.CURATED.PROVIDERS (
    PROVIDER_ID VARCHAR(50) PRIMARY KEY,
    PROVIDER_NAME VARCHAR(200) NOT NULL,
    SPECIALTY VARCHAR(100),
    NPI_NUMBER VARCHAR(20) UNIQUE,
    PRACTICE_LOCATION VARCHAR(500),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_BATCH_ID VARCHAR(100),
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    PIPELINE_VERSION VARCHAR(20)
);
