CREATE TABLE IF NOT EXISTS PA360_DEV.CURATED.PAYERS (
    PAYER_ID VARCHAR(50) PRIMARY KEY,
    PAYER_NAME VARCHAR(200) NOT NULL,
    CONTACT_INFO VARIANT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_BATCH_ID VARCHAR(100),
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    PIPELINE_VERSION VARCHAR(20)
);
