CREATE TABLE IF NOT EXISTS PA360_DEV.CURATED.PLANS (
    PLAN_ID VARCHAR(50) PRIMARY KEY,
    PLAN_NAME VARCHAR(200) NOT NULL,
    PAYER_ID VARCHAR(50) REFERENCES PA360_DEV.CURATED.PAYERS(PAYER_ID),
    PA_RULES_SUMMARY VARIANT,
    COPAY_INFO VARIANT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    EFFECTIVE_DATE DATE,
    TERMINATION_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_BATCH_ID VARCHAR(100),
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    PIPELINE_VERSION VARCHAR(20)
);
