CREATE TABLE IF NOT EXISTS PA360_DEV.CURATED.SERVICES (
    SERVICE_CODE VARCHAR(20) PRIMARY KEY,
    SERVICE_NAME VARCHAR(200),
    SPECIALTY VARCHAR(100),
    AUTHORIZATION_REQUIRED BOOLEAN NOT NULL,
    TYPICAL_DURATION_DAYS INTEGER,
    NOTES VARCHAR(1000),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_BATCH_ID VARCHAR(100),
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    PIPELINE_VERSION VARCHAR(20)
);
