CREATE TABLE IF NOT EXISTS PA360_DEV.CURATED.SAMPLE_DOCUMENTS (
    DOCUMENT_ID VARCHAR(36) PRIMARY KEY,
    AUTHORIZATION_ID VARCHAR(36) REFERENCES PA360_DEV.CURATED.AUTHORIZATION_REQUESTS(AUTHORIZATION_ID),
    DOCUMENT_TYPE VARCHAR(50),
    FILE_NAME VARCHAR(200),
    FILE_PATH VARCHAR(500),
    FILE_SIZE INTEGER,
    MIME_TYPE VARCHAR(100),
    EXTRACTED_TEXT TEXT,
    EXTRACTION_STATUS VARCHAR(20) DEFAULT 'PENDING',
    UPLOADED_BY_USER_ID VARCHAR(50),
    UPLOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_BATCH_ID VARCHAR(100),
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    PIPELINE_VERSION VARCHAR(20)
);
