CREATE TABLE IF NOT EXISTS PA360_DEV.CURATED.PAYER_RESPONSES (
    RESPONSE_ID VARCHAR(36) PRIMARY KEY,
    AUTHORIZATION_ID VARCHAR(36) REFERENCES PA360_DEV.CURATED.AUTHORIZATION_REQUESTS(AUTHORIZATION_ID),
    PAYER_ID VARCHAR(50) REFERENCES PA360_DEV.CURATED.PAYERS(PAYER_ID),
    PAYER_NAME VARCHAR(200),
    RESPONSE_TYPE VARCHAR(50),
    RESPONSE_DATE TIMESTAMP_NTZ,
    RESPONSE_TEXT TEXT,
    RAW_RESPONSE_DATA VARIANT,
    PROCESSED BOOLEAN DEFAULT FALSE,
    PROCESSED_AT TIMESTAMP_NTZ,
    AI_INTERPRETATION TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_BATCH_ID VARCHAR(100),
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    PIPELINE_VERSION VARCHAR(20)
);
