CREATE TABLE IF NOT EXISTS PA360_DEV.CURATED.AUDIT_LOGS (
    AUDIT_ID VARCHAR(36) PRIMARY KEY,
    ACTOR_USER_ID VARCHAR(50),
    ACTION VARCHAR(100) NOT NULL,
    ENTITY_TYPE VARCHAR(50),
    ENTITY_ID VARCHAR(50),
    BEFORE_STATE VARIANT,
    AFTER_STATE VARIANT,
    METADATA VARIANT,
    IP_ADDRESS VARCHAR(50),
    TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
