CREATE TABLE IF NOT EXISTS PA360_DEV.CURATED.SLA_CONFIGURATIONS (
    SLA_CONFIG_ID VARCHAR(36) PRIMARY KEY,
    PRIORITY VARCHAR(20) NOT NULL,
    PAYER_ID VARCHAR(50) REFERENCES PA360_DEV.CURATED.PAYERS(PAYER_ID),
    MAX_TURNAROUND_HOURS INTEGER NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_BATCH_ID VARCHAR(100),
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    PIPELINE_VERSION VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS PA360_DEV.CURATED.SLA_BREACHES (
    BREACH_ID VARCHAR(36) PRIMARY KEY,
    AUTHORIZATION_ID VARCHAR(36) REFERENCES PA360_DEV.CURATED.AUTHORIZATION_REQUESTS(AUTHORIZATION_ID),
    SLA_CONFIG_ID VARCHAR(36) REFERENCES PA360_DEV.CURATED.SLA_CONFIGURATIONS(SLA_CONFIG_ID),
    BREACH_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BREACH_HOURS INTEGER,
    NOTES TEXT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_BATCH_ID VARCHAR(100),
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    PIPELINE_VERSION VARCHAR(20)
);
