CREATE TABLE IF NOT EXISTS PA360_DEV.CURATED.USER_PROFILES (
    USER_ID VARCHAR(50) PRIMARY KEY,
    USERNAME VARCHAR(100) UNIQUE NOT NULL,
    EMAIL VARCHAR(200) UNIQUE NOT NULL,
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    ROLE VARCHAR(50) NOT NULL,
    DEPARTMENT VARCHAR(100),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    INGESTION_TIMESTAMP TIMESTAMP_NTZ,
    SOURCE_BATCH_ID VARCHAR(100),
    PROCESSING_STATUS VARCHAR(20) DEFAULT 'ACTIVE',
    PIPELINE_VERSION VARCHAR(20)
);
